/* ADV.H: Header file for AD&D games 

	Created by:  	Kevin Rattai
	Date created:	June 1, 1992

*/

int damage(int, int, int);
int dice(int, int);
int distance(void);
int doors(int);
int finddoor(int);
int findtrap(int);
int hit(int, int, int, int, int, int);
int initiative(int);
int morale(int, int);
int reaction(void);
int saving(int, int, int);
int surprise(void);
int traps(void);